spring.application.name=sission6
spring.datasource.url=jdbc:postgresql://localhost:5432/sision6
spring.datasource.username=postgres
spring.datasource.password=Vuhao2005@

# câu hình sql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update